sudo: required
services: 
  - docker

before_install:
  - docker build -t keerthikumarn/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true keerthikumarn/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker-react'
  env: 'Dockerreact-env-1'
  bucket_name: 'elasticbeanstalk-ap-south-1-967736777632'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'


